###recuperarr todas las peliculas
GET http://localhost:1234/movies
### recupera peliculas de genero accion y con rating de >= 8
GET  http://localhost:1234/movies?genre=Action&rate=8

### recupera peliculas de genero accion y con rating de >= 8 con un limite maximo de 3 pelis
GET  http://localhost:1234/movies?genre=Action&rate=8&limit=2

### request con limites no funcionales (me devuelve todas las busquedas para los otros filtros)
GET  http://localhost:1234/movies?genre=Action&rate=8&limit=1.4


### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### modificar una pelicula con PATCH
PATCH http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
Content-Type: application/json

{
    "year": 2020
}
